CREATE TABLE "user_encryption_keys" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"data_encryption_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Copy every existing DEK across before the column is dropped below. Hand-added:
-- drizzle-kit's autogenerated diff does not preserve data across a column move,
-- it would have just DROP COLUMN'd this away.
INSERT INTO "user_encryption_keys" ("user_id", "data_encryption_key")
SELECT "user_id", "data_encryption_key" FROM "user_profiles";
--> statement-breakpoint
ALTER TABLE "user_profiles" DROP COLUMN "data_encryption_key";