/**
 * Registry of DV sources loaded from dv-sources/<slug>/values.json.
 * China (CNS 2023) has its own seed: db/seed/seed-china-cns-2023.ts.
 */
import type { SourceMeta } from '../../../lib/dv/source-values';

export const SOURCES: Record<string, SourceMeta> = {
  USA_CANADA: {
    region: 'USA_CANADA',
    slug: 'nih-dri',
    authorityName: 'NIH/NAM Dietary Reference Intakes (USA + Canada)',
    versionYear: 2019,
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK545442/',
    note: 'National Academies DRI summary tables (Appendix J of the 2019 Sodium and Potassium report), parsed from HTML snapshots in dv-sources/nih-dri/source/. EAR, RDA/AI (AI marked *), UL, AMDR, sodium CDRR, added sugars limit (Table J-6). EER from the 2023 Energy DRI report, Appendix M Tables M-1 to M-4 (U.S., normal weight, median height/weight, 4 PAL categories); infants, 1-2 y and pregnancy EER are equations only. Protein EAR omitted: published per kg body weight.',
    retrievedDate: '2026-09-14',
  },
  EU: {
    region: 'EU',
    slug: 'efsa-drv',
    authorityName: 'EFSA Dietary Reference Values (NDA Panel) + Tolerable Upper Intake Levels',
    versionYear: 2017,
    url: 'https://www.efsa.europa.eu/sites/default/files/assets/DRV_Summary_tables_jan_17.pdf',
    note: 'EFSA DRV summary tables v4 (Sept 2017) and UL overview v11 (Aug 2025), transcribed cell by cell in dv-sources/efsa-drv/extract.ts. PRI stored as RDA, AR as EAR, energy AR as EER (MJ, by PAL). Thiamin and niacin stored per MJ. Protein (per kg), SFA/TFA (ALAP), EPA+DHA and safe levels of intake not stored.',
    retrievedDate: '2026-09-14',
  },
  JAPAN: {
    region: 'JAPAN',
    slug: 'mhlw-2025',
    authorityName: 'MHLW — Dietary Reference Intakes for Japanese (2025) 日本人の食事摂取基準（2025年版）',
    versionYear: 2025,
    url: 'https://www.mhlw.go.jp/content/10904750/001316585.pdf',
    note: '2025 edition (in force April 2025). Tables transcribed from the Kenpakusha reprint and checked cell by cell against the official MHLW report renders (dv-sources/mhlw-2025/extract.ts). DG ranges/floors as AMDR, ceilings as CDRR; sodium DG converted from salt g with the table ratio 2.54. Energy per activity level; pregnancy increments stored as totals over women 18-29 and 30-49 y. Iron for women 10-64 y stored for menstruating women. Magnesium UL (350 mg adults) applies to non-food sources only.',
    retrievedDate: '2026-09-17',
  },
  AU_NZ: {
    region: 'AU_NZ',
    slug: 'nhmrc-nrv',
    authorityName: 'NHMRC / NZ MoH — Nutrient Reference Values for Australia and New Zealand',
    versionYear: 2006,
    url: 'https://www.nhmrc.gov.au/about-us/publications/nutrient-reference-values-australia-and-new-zealand-including-recommended-dietary-intakes',
    note: 'NRV 2006 with the 2017 fluoride and sodium updates. Summary Tables 1, 2, 4-9 and chronic-disease Tables 1 (SDT) and 2 (AMDR) transcribed in dv-sources/nhmrc-nrv/extract.ts. RDI stored as RDA. n-6/n-3 AIs are total (Omega-6/Omega-3); LC n-3 as Long Chain Omega-3. Adult EER not stored (depends on height and weight).',
    retrievedDate: '2026-09-14',
  },
  NORDIC: {
    region: 'NORDIC',
    slug: 'nnr-2023',
    authorityName: 'Nordic Nutrition Recommendations 2023',
    versionYear: 2023,
    url: 'https://pub.norden.org/nord2023-003',
    note: 'NNR2023 Tables 8, 10, 12-21 and Boxes 2-8 transcribed in dv-sources/nnr-2023/extract.ts; merged superscripts read from the rendered pages. RI stored as RDA, AR (incl. provisional, flagged) as EAR, intake ranges as AMDR, energy reference values as EER (MJ, PAL 1.4/1.6/1.8 for adults). Thiamin and niacin per MJ. Protein and infant energy (per kg) not stored.',
    retrievedDate: '2026-09-14',
  },
  SPAIN: {
    region: 'SPAIN',
    slug: 'aesan-2019',
    authorityName: 'AESAN — Ingestas Nutricionales de Referencia (Spain 2019)',
    versionYear: 2019,
    url: 'https://www.aesan.gob.es/AECOSAN/docs/documentos/seguridad_alimentaria/evaluacion_riesgos/informes_comite/INR.pdf',
    note: 'AESAN-2019-003 INR for vitamins and minerals (Tables 6a-7d), parsed from a text snapshot in dv-sources/aesan-2019/source/. Only the AESAN INR column is stored; FESNAD/EFSA comparison columns and the EFSA-derived Tables 1-5 are not. INR stored as RDA although it also covers AI-derived values.',
    retrievedDate: '2026-09-14',
  },
  WHO_FAO: {
    region: 'WHO_FAO',
    slug: 'who-fao',
    authorityName: 'FAO/WHO — Vitamin and mineral requirements in human nutrition (2nd ed.)',
    versionYear: 2004,
    url: 'https://www.fao.org/4/y2809e/y2809e0o.htm',
    note: 'Vitamin and mineral RNIs: 2004 report Appendix 1 (FAO HTML). WHO guidelines: sodium, potassium (2012), free sugars (2015), saturated/trans fat, total fat, carbohydrate/fibre (2023) as CDRR. FAO/WHO/UNU 2001 energy requirements (infants, children). FAO 2010 fats and fatty acids Tables 2.1-2.2. Snapshots in dv-sources/who-fao/source/.',
    retrievedDate: '2026-09-14',
  },
  UK: {
    region: 'UK',
    slug: 'sacn-rni',
    authorityName: 'UK Dietary Reference Values (COMA 1991, SACN updates)',
    versionYear: 2016,
    url: 'https://www.nutrition.org.uk/media/nmmewdug/nutrition-requirements.pdf',
    note: 'COMA 1991 RNIs with SACN 2011 energy, 2015 carbohydrate/fibre and 2016 vitamin D, as reproduced in the British Nutrition Foundation summary (2021), transcribed in dv-sources/sacn-rni/extract.ts. RNI stored as RDA, energy EAR as EER (MJ). Salt maxima stored as sodium CDRR. Adult protein (per kg) not stored.',
    retrievedDate: '2026-09-14',
  },
  INDIA: {
    region: 'INDIA',
    slug: 'icmr-2020',
    authorityName: 'ICMR-NIN Nutrient Requirements for Indians (RDA and EAR 2020)',
    versionYear: 2020,
    url: 'https://www.nin.res.in/rdabook/brief_note.pdf',
    note: 'ICMR-NIN 2020 brief note, Tables 1a/1b, 2a, 3 and 4, transcribed in dv-sources/icmr-2020/extract.ts. Micronutrients for adults only (the full book is paid). Adult ages not given; stored from 18 y. Vitamin D converted from IU (1 µg = 40 IU).',
    retrievedDate: '2026-09-14',
  },
  SINGAPORE: {
    region: 'SINGAPORE',
    slug: 'hpb-singapore',
    authorityName: 'Singapore HPB / MOH — Recommended Dietary Allowances',
    versionYear: 2022,
    url: 'https://www.healthhub.sg/well-being-and-lifestyle/food-diet-and-nutrition/recommended_dietary_allowances',
    note: 'HealthHub RDA page (reviewed 15 Nov 2022), all tables incl. energy by activity level, transcribed in dv-sources/hpb-singapore/extract.ts from an HTML snapshot. Vitamin A as retinol equivalents; vitamin D 2.5 µg reflects tropical sunlight.',
    retrievedDate: '2026-09-14',
  },
  ITALY: {
    region: 'ITALY',
    slug: 'larn-2014',
    authorityName: 'SINU — LARN IV Revisione (Italy)',
    versionYear: 2014,
    url: 'https://eng.sinu.it/tabelle-larn-2014/',
    note: 'The 13 open LARN 2014 tables on eng.sinu.it, parsed from HTML snapshots in dv-sources/larn-2014/source/ (lipid and carbohydrate prose cells transcribed). PRI (bold) stored as RDA, AI (italic) as AI, AR as EAR, RI as AMDR, SDT as SDT. Energy stored for infants and children at median PAL; adult energy is printed per body height and not stored. Vitamin A as retinol equivalents. LARN V (2024) values are in the paid book and not used.',
    retrievedDate: '2026-09-16',
  },
  KOREA: {
    region: 'KOREA',
    slug: 'kdri-2020',
    authorityName: 'MOHW / Korean Nutrition Society — Dietary Reference Intakes for Koreans (KDRIs)',
    versionYear: 2020,
    url: 'https://www.kns.or.kr/',
    note: 'English summary tables, Book 1 Appendix 2 (printed pp. 255-264), transcribed cell by cell in dv-sources/kdri-2020/extract.ts from page renders, with the 2021 errata applied (amino acids). RNI stored as RDA. Pregnancy/lactation increments stored as totals over women 19-29 and 30-49 y. Methionine+Cysteine, Phe+Tyr and EPA+DHA (except infant DHA) not stored.',
    retrievedDate: '2026-09-16',
  },
  TAIWAN: {
    region: 'TAIWAN',
    slug: 'taiwan-dri-8',
    authorityName: 'Taiwan HPA — Dietary Reference Intakes, 8th edition (國人膳食營養素參考攝取量 第八版)',
    versionYear: 2022,
    url: 'https://www.hpa.gov.tw/',
    note: 'Total table (pp. 718-722) and UL table (p. 724), transcribed cell by cell in dv-sources/taiwan-dri-8/extract.ts from page renders; vitamin B6 from its chapter table (p. 330). Unmarked values are RDA, AI as marked. Energy and fibre per activity level (PAL 1.3/1.5/1.7/1.9). Pregnancy per trimester, stored as totals over women 19-30 and 31-50 y.',
    retrievedDate: '2026-09-16',
  },
  RUSSIA: {
    region: 'RUSSIA',
    slug: 'russia-mr-2021',
    authorityName: 'Rospotrebnadzor — MR 2.3.1.0253-21 Norms of physiological needs for energy and nutrients (Russia)',
    versionYear: 2021,
    url: 'https://www.garant.ru/products/ipo/prime/doc/402716140/',
    note: 'Official text of MR 2.3.1.0253-21 (approved 22 July 2021) as published by Garant, parsed from an HTML snapshot in dv-sources/russia-mr-2021/source/ (tables 7-23; subscript pictures read and mapped). Norms stored as RDA, adequate levels as AI, optimal energy shares as AMDR. Adult energy and macronutrients per activity level (КФА 1.4/1.6/1.9/2.2); 65+ at a single КФА 1.7. Pregnancy additions stored as totals.',
    retrievedDate: '2026-09-16',
  },
  DACH: {
    region: 'DACH',
    slug: 'dge-dach',
    authorityName: 'DGE / ÖGE / SGE — D-A-CH Referenzwerte für die Nährstoffzufuhr (Germany, Austria, Switzerland)',
    versionYear: 2025,
    url: 'https://www.dge.de/wissenschaft/referenzwerte-tool/',
    note: 'Current official values from the DGE Referenzwerte-Tool (all 16 population groups, all nutrients, both sexes), parsed from an HTML snapshot with footnotes in dv-sources/dge-dach/source/. Empfohlene Zufuhr stored as RDA, Schätzwert as AI, Richtwert as EER (energy), AI (water, fluoride) or AMDR (fat, carbohydrate, fibre). Zinc by phytate intake. Footnoted vitamin D supplementation UL, cholesterol, trans fat and free sugars limits stored. Protein (g/kg) not stored.',
    retrievedDate: '2026-09-17',
  },
  FRANCE: {
    region: 'FRANCE',
    slug: 'anses-2021',
    authorityName: 'ANSES — Actualisation des références nutritionnelles françaises en vitamines et minéraux (France)',
    versionYear: 2021,
    url: 'https://www.anses.fr/fr/system/files/NUT2018SA0238Ra.pdf',
    note: 'Avis 2018-SA-0238 (March 2021), summary Tableaux 2 and 3 transcribed from the PDF text layer and checked against page renders in dv-sources/anses-2021/source/. BNM stored as EAR, RNP as RDA, AS as AI, LSS as UL. B1 and B3 per MJ. Iron for low-to-moderate menstrual losses (high losses in notes). Zinc by phytate intake. Energy and macronutrients are separate ANSES opinions, not stored; manganese not set.',
    retrievedDate: '2026-09-17',
  },
  NETHERLANDS: {
    region: 'NETHERLANDS',
    slug: 'gr-netherlands',
    authorityName: 'Gezondheidsraad (Health Council of the Netherlands) — Voedingsnormen voor vitamines en mineralen',
    versionYear: 2025,
    url: 'https://www.gezondheidsraad.nl/documenten/adviezen/2025/04/23/advies-voedingsnormen-voor-vitamines-en-mineralen-voor-zuigelingen-en-kinderen',
    note: 'Adults from advice 2018/19 (Tabellen 3-4, https://www.gezondheidsraad.nl/documenten/2018/09/18/voedingsnormen-voor-vitamines-en-mineralen-voor-volwassenen); infants 7-11 months and children from advice 2025/06 (Tabellen 2-4, erratum 9 Sept 2025). Transcribed from the PDF text layers and checked against page renders in dv-sources/gr-netherlands/source/. Gemiddelde behoefte stored as EAR, aanbevolen hoeveelheid as RDA, adequate inname as AI. The adult origin (EFSA, NCM 2014, GR) is kept in notes. No values for infants under 7 months, pregnancy, lactation, upper levels or energy.',
    retrievedDate: '2026-09-17',
  },
  INDONESIA: {
    region: 'INDONESIA',
    slug: 'akg-indonesia-2019',
    authorityName: 'Kementerian Kesehatan — Angka Kecukupan Gizi (Permenkes No. 28 Tahun 2019) (Indonesia)',
    versionYear: 2019,
    url: 'https://peraturan.bpk.go.id/Details/138621/permenkes-no-28-tahun-2019',
    note: 'Lampiran I Tabel 1-3 of the Ministry of Health regulation (certified copy from stunting.go.id), transcribed from the PDF text layer and checked against page renders in dv-sources/akg-indonesia-2019/source/. AKG stored as RDA, energy as EER. Pregnancy (by trimester) and lactation (by 6-month period) increments stored as totals over women 19-29 and 30-49 y. No upper levels.',
    retrievedDate: '2026-09-17',
  },
  PHILIPPINES: {
    region: 'PHILIPPINES',
    slug: 'pdri-2015',
    authorityName: 'FNRI-DOST — Philippine Dietary Reference Intakes 2015 (Philippines)',
    versionYear: 2015,
    url: 'https://www.fnri.dost.gov.ph/images/images/news/PDRI-2018.pdf',
    note: 'PDRI 2015 Summary Tables (revised September 2018), all 7 pages. RNI vs AI read from the PDF font (bold RNI, italic AI; span dump in dv-sources/pdri-2015/source/), checked against page renders. REI stored as EER, RNI as RDA, AI, EAR, UL, AMDR; WHO additional recommendations (free sugars, sodium, potassium) as CDRR. Pregnancy/lactation increments stored as totals over women 19-29 and 30-49 y.',
    retrievedDate: '2026-09-17',
  },
  MALAYSIA: {
    region: 'MALAYSIA',
    slug: 'rni-malaysia-2017',
    authorityName: 'NCCFN, Ministry of Health Malaysia — Recommended Nutrient Intakes for Malaysia 2017',
    versionYear: 2017,
    url: 'https://hq.moh.gov.my/nutrition/wp-content/uploads/2023/12/FA-Buku-RNI.pdf',
    note: 'Full 523-page report. RNI 2017 Summary Tables 1-3b (energy by PAL, protein, vitamins, minerals), the macronutrient ranges in Appendix 3.5, Appendix 4.1 and the Energy & Macronutrients summary, and the upper levels printed in the chapters (all reproduced from IOM, noted per value). Transcribed from the PDF text layer and checked against renders in dv-sources/rni-malaysia-2017/source/. RNI stored as RDA, energy as EER, %TEI ranges as AMDR or CDRR, chapter ULs as UL.',
    retrievedDate: '2026-09-17',
  },
  VIETNAM: {
    region: 'VIETNAM',
    slug: 'vietnam-rda-2016',
    authorityName: 'Viện Dinh dưỡng, Bộ Y tế — Nhu cầu dinh dưỡng khuyến nghị cho người Việt Nam (2016)',
    versionYear: 2016,
    url: 'http://vichat.viendinhduong.vn/vi/nam-2016.nd81/diem-moi-ve-nhu-cau-khuyen-nghi-vitamin-va-khoang-chat-cho-nguoi-viet-nam.i289.html',
    note: 'Official book issued with decision 2615/QD-BYT (16 June 2016), 188 pages. Per-nutrient chapter tables (Bang 16-42, with EAR/RDA/AI/UL by sex) plus the appendix for energy by activity level, protein, fat and fatty acids, carbohydrate and fibre, and sodium/potassium/chloride. Transcribed from the PDF text layer. Iron stored at 10% bioavailability, zinc by absorption level, diet goals stored as CDRR. Amino acids (per kg / per g protein) and water (per kg / per kcal) are not stored.',
    retrievedDate: '2026-09-20',
  },
};
