/**
 * API Type Definitions - Compound Database System
 *
 * Generated by Backend-Architect for Feature System 05-compound-database-system
 * Phase 1: Browse Compounds
 *
 * IMPORTANT: Follow TypeScript conventions from /references/templates/backend/typescript-conventions.ts
 * - Use named exports only (no default exports)
 * - Use undefined instead of null
 * - All dates are ISO strings
 * - All IDs are strings
 */

// ============================================================================
// COMPOUND TYPES
// ============================================================================

/**
 * Compound Type Enum
 * Matches database ENUM: compound_type_enum
 * 20 scientifically-organized chemical categories
 */
export type CompoundType =
  | 'MACRONUTRIENT'           // Protein, Fat, Carbs, Energy, Water
  | 'VITAMIN'
  | 'MINERAL'
  | 'AMINO_ACID'
  | 'NUCLEOTIDE'              // Purines, uric acid
  | 'FATTY_ACID'
  | 'CARBOHYDRATE'
  | 'POLYPHENOL'
  | 'CAROTENOID'
  | 'ALKALOID'                // Caffeine, histamine, biogenic amines
  | 'GLUCOSINOLATE'
  | 'TERPENOID'
  | 'STEROL'                  // Phytosterols, ergosterols, etc.
  | 'ORGANIC_ACID'            // Citric acid, malic acid, lactic acid, etc.
  | 'MYCOTOXIN'               // Aflatoxin, ochratoxin - safety tracking
  | 'PESTICIDE_RESIDUE'       // Glyphosate, organophosphates - safety tracking
  | 'PLASTICIZER'             // BPA, phthalates - endocrine disruptor tracking
  | 'PROCESSING_COMPOUND'
  | 'SYNTHETIC_ADDITIVE'
  | 'ANTI_NUTRIENT';

/**
 * Confidence Level Enum
 * Based on 4-layer confidence scoring system
 */
export type ConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW' | 'GRAY_NULL';

/**
 * Confidence Level Numeric Ranges
 * HIGH: 80-100%, MEDIUM: 50-79%, LOW: 1-49%, GRAY_NULL: 0%
 */
export type ConfidenceScore = number; // 0-100

/**
 * Search Match Type
 * Indicates which tier of search cascade matched
 */
export type SearchMatchType = 'exact' | 'full-text' | 'fuzzy';

/**
 * Category Type Enum
 * FUNCTION: Functional categories (Bone Health, Heart Health, etc.)
 * CONDITION: Health condition categories (Histamine Management, Kidney Stone Prevention, etc.)
 */
export type CategoryType = 'FUNCTION' | 'CONDITION';

/**
 * Relevance Tier
 * 1 = PRIMARY (★ Key Nutrients)
 * 2 = SECONDARY (Also Supports)
 * 3 = TERTIARY (Related - collapsed by default)
 */
export type RelevanceTier = 1 | 2 | 3;

/**
 * Citation Quality Grade
 * Based on 18-point scoring system (0-18 total)
 * A*: 17-18, A: 14-16, B: 10-13, C: 0-9
 */
export type QualityGrade = 'A*' | 'A' | 'B' | 'C';

// ============================================================================
// DATABASE MODELS
// ============================================================================

/**
 * Compound - Core entity (280 compounds Phase 1)
 */
export interface Compound {
  id: string; // UUID
  compound_type: CompoundType;
  name: string;
  alternate_names: string[];
  unit: string;
  parent_compound_id: string | undefined; // FK to parent compound (self-referential)
  description: string | undefined;
  health_concern_flags: Record<string, unknown>; // JSONB
  formation_conditions: Record<string, unknown> | undefined; // JSONB
  iarc_group: string | undefined;
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
}

/**
 * Compound Source - UUID mapping system for cross-source deduplication
 */
export interface CompoundSource {
  id: string; // UUID
  compound_id: string; // FK to compounds
  external_source: string; // 'USDA', 'CNF', 'PubMed'
  external_id: string; // External system ID
  created_at: string; // ISO timestamp
}

/**
 * Research Citation - PubMed research articles
 */
export interface ResearchCitation {
  id: string; // UUID
  pmid: number; // PubMed ID (unique)
  study_design: string; // 'meta-analysis', 'RCT', 'cohort', etc.
  sample_size: number | undefined;
  quality_score_total: number; // 0-18 scale
  year: number;
  authors: string;
  title: string;
  journal: string;
  abstract: string | undefined;
  created_at: string; // ISO timestamp
}

/**
 * Compound Citation - Polymorphic junction table
 */
export interface CompoundCitation {
  id: string; // UUID
  compound_id: string; // FK to compounds
  citation_id: string; // FK to research_citations
  citable_type: string; // Polymorphic type
  citable_id: string; // Polymorphic ID (UUID)
  context: string | undefined;
  created_at: string; // ISO timestamp
}

/**
 * Functional Category - 18 functional + 15-18 condition categories
 */
export interface FunctionalCategory {
  id: string; // UUID
  name: string;
  type: CategoryType;
  description: string | undefined;
  created_at: string; // ISO timestamp
}

/**
 * Compound Category Mapping - Many-to-many junction
 */
export interface CompoundCategoryMapping {
  compound_id: string; // FK to compounds
  category_id: string; // FK to functional_categories
  relevance_tier: RelevanceTier; // 1=PRIMARY, 2=SECONDARY, 3=TERTIARY
}

// ============================================================================
// API REQUEST TYPES
// ============================================================================

/**
 * GET /api/compounds - List compounds with filters
 */
export interface GetCompoundsRequest {
  category?: CompoundType; // Filter by chemical type
  healthCondition?: string; // Filter by health condition ID (UUID)
  confidenceLevel?: ConfidenceLevel; // Filter by confidence
  hasRDA?: boolean; // Filter compounds with RDA defined
  limit?: number; // Pagination limit (default 50)
  offset?: number; // Pagination offset (default 0)
}

/**
 * GET /api/compounds/[id] - Get compound detail
 * Path parameter: id (UUID)
 */
export interface GetCompoundByIdRequest {
  id: string; // Compound UUID
}

/**
 * GET /api/compounds/search - Search compounds with autocomplete
 */
export interface SearchCompoundsRequest {
  q: string; // Search query (min 3 characters)
  limit?: number; // Results limit (default 10)
}

/**
 * GET /api/categories - Get functional categories
 */
export interface GetCategoriesRequest {
  type?: CategoryType; // Filter by FUNCTION or CONDITION
}

/**
 * GET /api/health-conditions - Get health condition categories
 * (Alias for GET /api/categories?type=CONDITION)
 */
export interface GetHealthConditionsRequest {
  // No additional parameters
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

/**
 * Standard API Response Wrapper
 * T = data payload type
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string; // Error message (undefined if success)
}

/**
 * Paginated Response Metadata
 */
export interface PaginationMeta {
  total: number; // Total count of items
  limit: number; // Items per page
  offset: number; // Current offset
}

/**
 * Compound List Item (simplified for list views)
 */
export interface CompoundListItem {
  id: string;
  name: string;
  compound_type: CompoundType;
  unit: string;
  description: string | undefined;
  confidence_score?: ConfidenceScore; // Optional, calculated from 4-layer formula
}

/**
 * Compound Detail (full data with relationships)
 */
export interface CompoundDetail {
  id: string;
  name: string;
  alternate_names: string[];
  compound_type: CompoundType;
  unit: string;
  description: string | undefined;
  health_concern_flags: Record<string, unknown>;
  parent_compound?: {
    id: string;
    name: string;
  };
  categories: Array<{
    id: string;
    name: string;
    type: CategoryType;
    relevance_tier: RelevanceTier;
  }>;
  citations: CitationListItem[]; // Paginated (10 per page)
}

/**
 * Citation List Item (for compound detail page)
 */
export interface CitationListItem {
  id: string;
  pmid: number;
  title: string;
  authors: string;
  year: number;
  journal: string;
  quality_score: number; // 0-18
  quality_grade: QualityGrade; // A*, A, B, C
}

/**
 * Search Result Item
 */
export interface SearchResult {
  id: string;
  name: string;
  compound_type: CompoundType;
  match_type: SearchMatchType; // 'exact' | 'full-text' | 'fuzzy'
  similarity?: number; // For fuzzy matches (0.0-1.0)
}

/**
 * Category List Item (with compound count)
 */
export interface CategoryListItem {
  id: string;
  name: string;
  type: CategoryType;
  description: string | undefined;
  compound_count: number; // Computed count of associated compounds
}

// ============================================================================
// API RESPONSE INTERFACES
// ============================================================================

/**
 * GET /api/compounds - Response
 */
export interface GetCompoundsResponse {
  compounds: CompoundListItem[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * GET /api/compounds/[id] - Response
 */
export type GetCompoundByIdResponse = CompoundDetail;

/**
 * GET /api/compounds/search - Response
 */
export interface SearchCompoundsResponse {
  results: SearchResult[];
}

/**
 * GET /api/categories - Response
 */
export interface GetCategoriesResponse {
  categories: CategoryListItem[];
}

/**
 * GET /api/health-conditions - Response
 */
export type GetHealthConditionsResponse = GetCategoriesResponse;

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Extract API endpoint path from request type
 */
export type ApiEndpoint =
  | '/api/compounds'
  | '/api/compounds/[id]'
  | '/api/compounds/search'
  | '/api/categories'
  | '/api/health-conditions';

/**
 * Map endpoint to request type
 */
export type ApiRequestMap = {
  '/api/compounds': GetCompoundsRequest;
  '/api/compounds/[id]': GetCompoundByIdRequest;
  '/api/compounds/search': SearchCompoundsRequest;
  '/api/categories': GetCategoriesRequest;
  '/api/health-conditions': GetHealthConditionsRequest;
};

/**
 * Map endpoint to response type
 */
export type ApiResponseMap = {
  '/api/compounds': ApiResponse<GetCompoundsResponse>;
  '/api/compounds/[id]': ApiResponse<GetCompoundByIdResponse>;
  '/api/compounds/search': ApiResponse<SearchCompoundsResponse>;
  '/api/categories': ApiResponse<GetCategoriesResponse>;
  '/api/health-conditions': ApiResponse<GetHealthConditionsResponse>;
};

// ============================================================================
// ERROR TYPES
// ============================================================================

/**
 * API Error Response
 */
export interface ApiError {
  success: false;
  error: string;
  code?: string; // Error code for programmatic handling
  details?: Record<string, unknown>; // Additional error details
}

/**
 * Validation Error (for request validation failures)
 */
export interface ValidationError extends Omit<ApiError, 'details'> {
  code: 'VALIDATION_ERROR';
  details: {
    field: string;
    message: string;
  }[];
}

/**
 * Not Found Error (404)
 */
export interface NotFoundError extends Omit<ApiError, 'details'> {
  code: 'NOT_FOUND';
  details: {
    resource: string; // 'compound', 'category', etc.
    id: string;
  };
}

/**
 * Rate Limit Error (429)
 */
export interface RateLimitError extends ApiError {
  code: 'RATE_LIMIT_EXCEEDED';
  details: {
    limit: number;
    window: string; // '1 minute', '1 hour', etc.
    retry_after: number; // Seconds until retry allowed
  };
}

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard for ApiResponse success
 */
export function isApiSuccess<T>(
  response: ApiResponse<T>
): response is ApiResponse<T> & { success: true; data: T } {
  return response.success === true && response.data !== undefined;
}

/**
 * Type guard for ApiResponse error
 */
export function isApiError<T>(
  response: ApiResponse<T>
): response is ApiResponse<T> & { success: false; error: string } {
  return response.success === false && response.error !== undefined;
}

/**
 * Type guard for ValidationError
 */
export function isValidationError(error: ApiError | ValidationError | NotFoundError): error is ValidationError {
  return error.code === 'VALIDATION_ERROR';
}

/**
 * Type guard for NotFoundError
 */
export function isNotFoundError(error: ApiError | ValidationError | NotFoundError): error is NotFoundError {
  return error.code === 'NOT_FOUND';
}

/**
 * Type guard for RateLimitError
 */
export function isRateLimitError(error: ApiError): error is RateLimitError {
  return error.code === 'RATE_LIMIT_EXCEEDED';
}

// ============================================================================
// EXPORTS
// ============================================================================

/**
 * All API types exported as named exports (following TypeScript conventions)
 * NO default exports
 */
