import 'dotenv/config';
import { db } from '../db';
import { compounds, compoundSources } from '../db/schema';
import { eq, sql } from 'drizzle-orm';

/**
 * FooDB Compound Import Script
 * 
 * Adds 388 new compounds and creates 559 FooDB mappings
 * Based on FooDB health-effect compounds appearing in 10+ foods
 */

// New compounds to add (388)
const newCompounds = [
  { foodbId: '13713', name: '(+)-1(10),4-Cadinadiene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14503', name: '(+)-Neomenthol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14723', name: '(+)-Syringaresinol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14965', name: '(-)-3-Isothujone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14915', name: '(-)-Isopulegol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15552', name: '(-)-Maackiain', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14420', name: '(-)-Matairesinol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14502', name: '(-)-Menthol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '13803', name: '(-)-Menthone', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '1170', name: '(-)-Quinic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '14898', name: '(3E,6E)-alpha-Farnesene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '19872', name: '(3R,3\'R, all-E)-Zeaxanthin', type: 'CAROTENOID' as const, unit: 'ug' },
  { foodbId: '8091', name: '(E)-2-Hexen-1-ol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2449', name: '(E)-Resveratrol 3-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2239', name: '(E)-Zeatin', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14300', name: '(R)-Limonene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14301', name: '(R)-p-Menth-4(8)-en-3-one', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13864', name: '(S)-Limonene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '678', name: '(S)-Naringenin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2089', name: '(S)-Reticuline', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '1108', name: '(S)-[6]-Gingerol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8092', name: '(Z)-3-Hexen-1-ol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14297', name: '(Z)-3-Methyl-2-(2-pentenyl)-2-cyclopenten-1-one', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8307', name: '(Z)-Aconitic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12389', name: '(Z)-Resveratrol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12763', name: '(Z,Z)-9,12-Octadecadienoic acid', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '13577', name: '(±)-Borneol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12449', name: '(±)-Citronellyl acetate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '14118', name: '(±)-Limonene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '9779', name: '(±)-Menthone', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '13762', name: '(±)-Myrtenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1512', name: '1,2-Benzenediol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14619', name: '1,8-Cineole', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12354', name: '1-Decanol', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '8073', name: '1-Hexanol', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '17365', name: '1-Isopropyl-4-methylbenzene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12395', name: '1-Methoxy-4-(2-propenyl)benzene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12762', name: '1-Octacosanol', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '8231', name: '1-Pentanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '12553', name: '1-Propanethiol', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '1365', name: '1H-Indole-3-acetonitrile', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '11933', name: '2,3-Butanedione', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12561', name: '2-Furanmethanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '8056', name: '2-Heptanone', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '14798', name: '2-Isopropyl-5-methylphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '857', name: '2-Methoxy-4-vinylphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11888', name: '2-Methoxyphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3275', name: '2-Methyl-1-propanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '8786', name: '2-Methylphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3272', name: '2-Methylpropanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3278', name: '2-Methylpropanoic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3276', name: '2-Methylpropyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12117', name: '2-Nonanol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3309', name: '2-Nonanone', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12155', name: '2-Phenylethanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '10582', name: '2-Phenylethylamine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11834', name: '2-Undecanone', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '14441', name: '24-Methylenecycloartan-3-ol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12063', name: '3,4-Dihydroxybenzaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '15484', name: '3,5,8-Megastigmatrien-7-one', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2628', name: '3,5-Di-O-caffeoylquinic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8858', name: '3-(3,4-Dihydroxyphenyl)propanoic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8542', name: '3-(Methylthio)propanal', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '12443', name: '3-Isothiocyanato-1-propene', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '3286', name: '3-Methylbutanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '1324', name: '3-Methylbutanoic acid', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '3344', name: '3-Octanol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8782', name: '3-Phenyl-2-propenal', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '10551', name: '4\'-Methylacetophenone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13519', name: '4(10)-Thujene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '8394', name: '4-Hexyl-gamma-butyrolactone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '822', name: '4-Hydroxy-3,5-dimethoxybenzaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '10506', name: '4-Hydroxybenzaldehyde', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '10510', name: '4-Hydroxybenzoic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13514', name: '4-Hydroxyproline', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '872', name: '4-Methoxybenzaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8175', name: '4-Methyl-2-pentanone', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8790', name: '4-Methylphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '22615', name: '5-Aminolevulinic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '14515', name: '5-Isopropyl-2-methylphenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15496', name: '6-Methoxy-2(3H)-benzoxazolone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17407', name: '7-Methyl-3-methylene-1,6-octadiene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '8298', name: 'Acetaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12396', name: 'Aceteugenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8302', name: 'Acetone', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12109', name: 'Acetophenone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3555', name: 'Adenosine', type: 'NUCLEOTIDE' as const, unit: 'mg' },
  { foodbId: '2999', name: 'Adipostatin A', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2775', name: 'Aesculetin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1613', name: 'Allantoin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '558', name: 'Alliin', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '8430', name: 'Allithiamine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8313', name: 'Allyl alcohol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '3909', name: 'Ammonia', type: 'MINERAL' as const, unit: 'mg' },
  { foodbId: '13639', name: 'Amygdalin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2793', name: 'Anethole', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '775', name: 'Angelic acid', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '2193', name: 'Anonaine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14614', name: 'Antheraxanthin', type: 'CAROTENOID' as const, unit: 'ug' },
  { foodbId: '5457', name: 'Anthocyanins', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '896', name: 'Anthranilic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16369', name: 'Apigenin 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2801', name: 'Apiin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11932', name: 'Apiole', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1221', name: 'Arbutin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14079', name: 'Arnidenediol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2806', name: 'Aromadendrin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16485', name: 'Astragalin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2820', name: 'Avicularin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14664', name: 'Benzaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3368', name: 'Benzyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8746', name: 'Benzyl alcohol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12847', name: 'Benzyl benzoate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2542', name: 'Bergapten', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '497', name: 'Betanin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15793', name: 'Betulin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1532', name: 'Betulinic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12226', name: 'Biochanin A', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12841', name: 'Biphenyl', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '9030', name: 'Bornyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12343', name: 'Brassinolide', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '3379', name: 'Butanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3578', name: 'Calcium oxalate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '9066', name: 'Camphene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14908', name: 'Carnosic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14817', name: 'Carnosol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14922', name: 'Carveol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1182', name: 'Cellulose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '801', name: 'Chalconaringenin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16256', name: 'Chlorine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16599', name: 'Chlorophyll', type: 'CAROTENOID' as const, unit: 'ug' },
  { foodbId: '16519', name: 'Chrysoeriol 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '887', name: 'Cinnamyl alcohol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '14620', name: 'Citronellal', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14493', name: 'Citronellol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15501', name: 'Coniferin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1513', name: 'Coniferyl aldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '11666', name: 'Coumestrol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2561', name: 'Cryptochlorogenic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8725', name: 'Cuminaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8493', name: 'Cuminyl alcohol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2597', name: 'Cyanidin 3,5-diglucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17166', name: 'Cyanidin 3-galactoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2603', name: 'Cyanidin 3-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '7050', name: 'Cyanidin 3-rutinoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15507', name: 'Cycloartenol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14885', name: 'Cycloeucalenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '9068', name: 'D-Camphor', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12531', name: 'D-Fructose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '12706', name: 'D-Galactose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '11679', name: 'D-Glucitol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '12533', name: 'D-Glucose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '1982', name: 'D-Mannitol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '1202', name: 'D-Mannose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '1136', name: 'D-Xylose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '10670', name: 'Dalbergioidin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12771', name: 'Decanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '19882', name: 'Decyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '17198', name: 'Delphinidin 3-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12199', name: 'Di-2-propenyl disulfide, 9CI', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '1400', name: 'Dihydrozeatin', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '3492', name: 'Dimethyl disulfide', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '3592', name: 'Dimethyl sulfide', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '12592', name: 'Dimethylamine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '8046', name: 'Dipropyl disulfide', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '12166', name: 'Dopamine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11935', name: 'Elemicin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12801', name: 'Estrone', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '753', name: 'Ethanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '3279', name: 'Ethyl 2-methylpropanoate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3241', name: 'Ethyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12200', name: 'Ethyl benzoate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12085', name: 'Ethyl butyrate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12005', name: 'Ethyl cinnamate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11950', name: 'Ethyl dodecanoate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '3254', name: 'Ethyl formate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1022', name: 'Ethyl hexadecanoate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '1326', name: 'Ethyl isovalerate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '20553', name: 'Ethyl lactate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '10562', name: 'Ethyl phenylacetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '1366', name: 'Ethyl propionate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '754', name: 'Ethylene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12174', name: 'Eugenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12152', name: 'Falcarindiol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11804', name: 'Falcarinone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14518', name: 'Farnesal', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14894', name: 'Farnesol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14522', name: 'Fenchone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '9446', name: 'Formaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12807', name: 'Formic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12222', name: 'Formononetin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12223', name: 'Formononetin 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '844', name: 'Gentisic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13705', name: 'Geranial', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '8530', name: 'Geranylacetone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3857', name: 'Germacrene D', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17782', name: 'Glucobrassicanapin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17792', name: 'Gluconapin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '22831', name: 'Glucosamine', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '1498', name: 'Glutathione', type: 'GLUCOSINOLATE' as const, unit: 'mg' },
  { foodbId: '1480', name: 'Hentriacontane', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8055', name: 'Heptyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8069', name: 'Hexanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '765', name: 'Hexane', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1267', name: 'Hexyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '11711', name: 'Hexyl butyrate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '10856', name: 'Hexyl formate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '885', name: 'Hydroquinone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3299', name: 'Hydroxyacetic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2711', name: 'Hyperin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12755', name: 'Imperatorin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12011', name: 'Indole', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '11805', name: 'Inosine', type: 'NUCLEOTIDE' as const, unit: 'mg' },
  { foodbId: '4039', name: 'Isochlorogenic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2728', name: 'Isoeugenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16342', name: 'Isoliquiritigenin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12398', name: 'Isoorientin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8133', name: 'Isopentyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8132', name: 'Isopentyl alcohol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '12664', name: 'Isopimpinellin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '21773', name: 'Isorhamnetin 3-O-b-D-glucopyranoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '614', name: 'Isovitexin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15497', name: 'Jasmonic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2824', name: 'Kaempferol 3-galactoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16502', name: 'Kaempferol 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12519', name: 'Kievitone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14509', name: 'L-5-Oxo-2-pyrrolidinecarboxylic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1224', name: 'L-Ascorbic acid', type: 'VITAMIN' as const, unit: 'mg' },
  { foodbId: '505', name: 'L-Canavanine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '567', name: 'L-DOPA', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1491', name: 'L-Homocysteine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '463', name: 'L-Stachydrine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13805', name: 'Lanosterol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12140', name: 'Lauric aldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '17706', name: 'Leucocyanidin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '18314', name: 'Leucodelphinidin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '7687', name: 'Leucopelargonidin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12167', name: 'Levoglutamide', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12401', name: 'Licoisoflavone A', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '5956', name: 'Lignans', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '9722', name: 'Lignin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13570', name: 'Limonene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '19140', name: 'Linalyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '11812', name: 'Linamarin', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '17857', name: 'Linustatin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12052', name: 'Lotaustralin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13644', name: 'Lupeol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14283', name: 'Luteolin 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2712', name: 'Maltol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12001', name: 'Medicagol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '4235', name: 'Melatonin', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '8125', name: 'Methanol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '1325', name: 'Methyl 3-methylbutanoate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '8126', name: 'Methyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12201', name: 'Methyl benzoate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12087', name: 'Methyl butyrate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '3338', name: 'Methyl caprylate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '12004', name: 'Methyl cinnamate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13899', name: 'Methyl hexanoate', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '12462', name: 'Methyl salicylate', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3959', name: 'Methylamine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '8549', name: 'Methyleugenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '21545', name: 'Methylisoeugenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '10549', name: 'Myo-Inositol', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '14657', name: 'Myristicin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13913', name: 'Myrtenal', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '4729', name: 'N-Heneicosane', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13919', name: 'N2-gamma-L-Glutamyl-L-arginine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '954', name: 'Naphthalene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11869', name: 'Naringin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11871', name: 'Narirutin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2562', name: 'Neochlorogenic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17853', name: 'Neolinustatin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '13578', name: 'Neral', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '14948', name: 'Nerol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14381', name: 'Nerolidol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14949', name: 'Neryl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '4237', name: 'Nicotianamine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3969', name: 'Nicotine', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '3304', name: 'Nonanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3340', name: 'Octanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '13037', name: 'Oleanolic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2510', name: 'Orientin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '21462', name: 'Pectic acid', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '12756', name: 'Pedunculagin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3229', name: 'Pentanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3231', name: 'Pentanoic acid', type: 'FATTY_ACID' as const, unit: 'g' },
  { foodbId: '17315', name: 'Peonidin 3-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14913', name: 'Perillaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '17324', name: 'Petunidin 3-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '893', name: 'Phenol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12241', name: 'Phenylacetaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '7171', name: 'Pheophytin A', type: 'CAROTENOID' as const, unit: 'ug' },
  { foodbId: '13882', name: 'Phloroglucinol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '5557', name: 'Phosphatidylethanolamine', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '545', name: 'Pipecolic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12647', name: 'Piperidine', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '13576', name: 'Piperitone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '958', name: 'Procyanidin B1', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12207', name: 'Procyanidin B2', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12208', name: 'Procyanidin B3', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12209', name: 'Procyanidin B4', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17717', name: 'Procyanidin C1', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '16781', name: 'Prodelphinidin B3', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12086', name: 'Propanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '8118', name: 'Propanedioic acid', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12403', name: 'Prunetin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12608', name: 'Psoralen', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14736', name: 'Pyridine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11958', name: 'Quercetin 3-arabinoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2536', name: 'Quercetin 3-rutinoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2523', name: 'Quercetin 7-glucoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11887', name: 'Quercitrin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11857', name: 'Quinoline', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '2829', name: 'Rhamnetin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '18292', name: 'Rhoifolin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '17468', name: 'Rosmadial', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2427', name: 'Rosmarinic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14609', name: 'Rubixanthin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15009', name: 'S-beta-Bisabolene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11675', name: 'Safrole', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3694', name: 'Salicylates', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2463', name: 'Schaftoside', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12708', name: 'Scopoletin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12161', name: 'Serotonin', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '4189', name: 'Silver', type: 'MINERAL' as const, unit: 'mg' },
  { foodbId: '1515', name: 'Sinapaldehyde', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '12101', name: 'Solanidine', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '13947', name: 'Solasodine', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '12042', name: 'Spermidine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '3226', name: 'Spermine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '15784', name: 'Squalene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '12555', name: 'Styrene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '514', name: 'Syringic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2412', name: 'Tangeritin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14717', name: 'Taraxasterol', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '13508', name: 'Taraxerol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '18814', name: 'Tellimagrandin II', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15973', name: 'Terpinolene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11547', name: 'Testosterone', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '15499', name: 'Tetramethylpyrazine', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12457', name: 'Toluene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2440', name: 'Tricin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2237', name: 'Trigonelline', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '11947', name: 'Trimethylamine', type: 'AMINO_ACID' as const, unit: 'mg' },
  { foodbId: '917', name: 'Tryptamine', type: 'ALKALOID' as const, unit: 'mg' },
  { foodbId: '1094', name: 'Umbelliferone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2917', name: 'Undecanal', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '3728', name: 'Uranium', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '838', name: 'Vanillin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2630', name: 'Vicenin 2', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2501', name: 'Vitexin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12477', name: 'Xanthotoxin', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15345', name: 'alpha-Cadinol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14327', name: 'alpha-Carene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3905', name: 'alpha-Cedrene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1522', name: 'alpha-Copaene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '5327', name: 'alpha-Curcumene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '6368', name: 'alpha-Elemol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15364', name: 'alpha-Humulene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14487', name: 'alpha-Ionone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14570', name: 'alpha-Selinene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14419', name: 'alpha-Terpineol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '1525', name: 'alpha-Ylangene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '1304', name: 'alpha1-Sitosterol', type: 'STEROL' as const, unit: 'mg' },
  { foodbId: '4093', name: 'beta-Amyrin', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '15740', name: 'beta-Caryophyllene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '11827', name: 'beta-D-Glucopyranose', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '22060', name: 'beta-D-Glucuronic acid', type: 'CARBOHYDRATE' as const, unit: 'g' },
  { foodbId: '14580', name: 'beta-Elemene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3840', name: 'beta-Eudesmol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15473', name: 'beta-Ionone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14920', name: 'beta-Phellandrene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15468', name: 'beta-Pinene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '13604', name: 'beta-Selinene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15019', name: 'beta-Sesquiphellandrene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15977', name: 'beta-Terpineol', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '1462', name: 'cis-beta-Ocimene', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '2432', name: 'd-Tocopherol', type: 'VITAMIN' as const, unit: 'mg' },
  { foodbId: '4663', name: 'epsilon-Carotene', type: 'CAROTENOID' as const, unit: 'ug' },
  { foodbId: '3393', name: 'gamma-Butyrolactone', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '15975', name: 'gamma-Terpinene', type: 'TERPENOID' as const, unit: 'mg' },
  { foodbId: '3387', name: 'n-Butyl acetate', type: 'ORGANIC_ACID' as const, unit: 'mg' },
  { foodbId: '11261', name: 'o-Coumaric acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '14604', name: 'p-Menth-1-en-4-ol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '3876', name: 'trans-Carveol', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '12805', name: 'trans-Ferulic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
  { foodbId: '10559', name: 'trans-Sinapic acid', type: 'POLYPHENOL' as const, unit: 'mg' },
];

// Existing compounds - just need FooDB ID mappings (171)  
const existingMappings = [
  { foodbId: '17773', foodbName: '4-Hydroxyglucobrassicin', nutriName: '4-Hydroxyglucobrassicin' },
  { foodbId: '12269', foodbName: 'Adenine', nutriName: 'Adenine' },
  { foodbId: '12193', foodbName: 'Allicin', nutriName: 'Allicin' },
  { foodbId: '3571', foodbName: 'Aluminum', nutriName: 'Aluminum' },
  { foodbId: '2798', foodbName: 'Apigenin', nutriName: 'Apigenin' },
  { foodbId: '11875', foodbName: 'Arachidonic acid', nutriName: 'Arachidonic Acid' },
  { foodbId: '2257', foodbName: 'Arginine', nutriName: 'Arginine' },
  { foodbId: '3764', foodbName: 'Arsenic', nutriName: 'Arsenic' },
  { foodbId: '8740', foodbName: 'Benzoic acid', nutriName: 'Benzoic Acid' },
  { foodbId: '9021', foodbName: 'Betaine', nutriName: 'Betaine' },
  { foodbId: '14513', foodbName: 'Biotin', nutriName: 'Biotin' },
  { foodbId: '3576', foodbName: 'Boron', nutriName: 'Boron' },
  { foodbId: '1493', foodbName: 'Cadaverine', nutriName: 'Cadaverine' },
  { foodbId: '3767', foodbName: 'Cadmium', nutriName: 'Cadmium' },
  { foodbId: '2558', foodbName: 'Caffeic acid', nutriName: 'Caffeic Acid' },
  { foodbId: '2100', foodbName: 'Caffeine', nutriName: 'Caffeine' },
  { foodbId: '3514', foodbName: 'Calcium', nutriName: 'Calcium' },
  { foodbId: '12524', foodbName: 'Campesterol', nutriName: 'Campesterol' },
  { foodbId: '14617', foodbName: 'Carvone', nutriName: 'Carvone' },
  { foodbId: '2571', foodbName: 'Catechin', nutriName: 'Catechin' },
  { foodbId: '1111', foodbName: 'Chinese tannin', nutriName: 'Tannic Acid' },
  { foodbId: '13272', foodbName: 'Cholesterol', nutriName: 'Cholesterol' },
  { foodbId: '710', foodbName: 'Choline', nutriName: 'Choline' },
  { foodbId: '3517', foodbName: 'Chromium', nutriName: 'Chromium' },
  { foodbId: '2579', foodbName: 'Chrysoeriol', nutriName: 'Chrysoeriol' },
  { foodbId: '12055', foodbName: 'Cinnamic acid', nutriName: 'Cinnamic Acid' },
  { foodbId: '3582', foodbName: 'Cobalt', nutriName: 'Cobalt' },
  { foodbId: '3583', foodbName: 'Copper', nutriName: 'Copper' },
  { foodbId: '12295', foodbName: 'Curcumin', nutriName: 'Curcumin' },
  { foodbId: '2602', foodbName: 'Cyanidin', nutriName: 'Cyanidin' },
  { foodbId: '2608', foodbName: 'Daidzein', nutriName: 'Daidzein' },
  { foodbId: '12228', foodbName: 'Daidzin', nutriName: 'Daidzin' },
  { foodbId: '12030', foodbName: 'Decanoic acid', nutriName: 'Capric Acid' },
  { foodbId: '2613', foodbName: 'Delphinidin', nutriName: 'Delphinidin' },
  { foodbId: '861', foodbName: 'Diosmetin', nutriName: 'Diosmetin' },
  { foodbId: '3004', foodbName: 'Doconexent', nutriName: 'Docosahexaenoic Acid' },
  { foodbId: '3011', foodbName: 'Dodecanoic acid', nutriName: 'Lauric Acid' },
  { foodbId: '3103', foodbName: 'Eicosapentaenoic acid', nutriName: 'Eicosapentaenoic Acid' },
  { foodbId: '12578', foodbName: 'Ellagic acid', nutriName: 'Ellagic Acid' },
  { foodbId: '17121', foodbName: 'Epicatechin 3-gallate', nutriName: 'Epicatechin-3-gallate' },
  { foodbId: '17707', foodbName: 'Epigallocatechin', nutriName: 'Epigallocatechin' },
  { foodbId: '12615', foodbName: 'Ergosterol', nutriName: 'Ergosterol' },
  { foodbId: '4288', foodbName: 'Erucic acid', nutriName: 'Erucic Acid' },
  { foodbId: '12804', foodbName: 'Ferulic acid', nutriName: 'Ferulic Acid' },
  { foodbId: '4486', foodbName: 'Fluoride', nutriName: 'Fluoride' },
  { foodbId: '14507', foodbName: 'Folic acid', nutriName: 'Folic Acid' },
  { foodbId: '3292', foodbName: 'Fumaric acid', nutriName: 'Fumaric Acid' },
  { foodbId: '657', foodbName: 'Galangin', nutriName: 'Galangin' },
  { foodbId: '662', foodbName: 'Gallic acid', nutriName: 'Gallic Acid' },
  { foodbId: '17712', foodbName: 'Gallocatechin', nutriName: 'Gallocatechin' },
  { foodbId: '2944', foodbName: 'Gamolenic acid', nutriName: 'Gamma-Linolenic Acid' },
  { foodbId: '11831', foodbName: 'Genistein', nutriName: 'Genistein' },
  { foodbId: '12224', foodbName: 'Genistin', nutriName: 'Genistin' },
  { foodbId: '13795', foodbName: 'Geraniol', nutriName: 'Geraniol' },
  { foodbId: '2066', foodbName: 'Glucobrassicin', nutriName: 'Glucobrassicin' },
  { foodbId: '17767', foodbName: 'Glucoiberin', nutriName: 'Glucoiberin' },
  { foodbId: '17788', foodbName: 'Gluconasturtiin', nutriName: 'Gluconasturtiin' },
  { foodbId: '17763', foodbName: 'Glucoraphanin', nutriName: 'Glucoraphanin' },
  { foodbId: '756', foodbName: 'Glycerol', nutriName: 'Glycerol' },
  { foodbId: '484', foodbName: 'Glycine', nutriName: 'Glycine' },
  { foodbId: '698', foodbName: 'Glycitein', nutriName: 'Glycitein' },
  { foodbId: '4223', foodbName: 'Guanine', nutriName: 'Guanine' },
  { foodbId: '4677', foodbName: 'Heptadecanoic acid', nutriName: 'Heptadecanoic Acid' },
  { foodbId: '2677', foodbName: 'Hesperetin', nutriName: 'Hesperetin' },
  { foodbId: '2680', foodbName: 'Hesperidin', nutriName: 'Hesperidin' },
  { foodbId: '13900', foodbName: 'Hexanoic acid', nutriName: 'Caproic Acid' },
  { foodbId: '12599', foodbName: 'Histamine', nutriName: 'Histamine' },
  { foodbId: '1141', foodbName: 'Inulin', nutriName: 'Inulin' },
  { foodbId: '3636', foodbName: 'Iodine', nutriName: 'Iodine' },
  { foodbId: '16258', foodbName: 'Iron', nutriName: 'Iron' },
  { foodbId: '604', foodbName: 'Isorhamnetin', nutriName: 'Isorhamnetin' },
  { foodbId: '633', foodbName: 'Kaempferol', nutriName: 'Kaempferol' },
  { foodbId: '556', foodbName: 'L-Alanine', nutriName: 'Alanine' },
  { foodbId: '787', foodbName: 'L-Asparagine', nutriName: 'Asparagine' },
  { foodbId: '12570', foodbName: 'L-Aspartic acid', nutriName: 'Aspartic Acid' },
  { foodbId: '11844', foodbName: 'L-Citrulline', nutriName: 'Citrulline' },
  { foodbId: '12681', foodbName: 'L-Cysteine', nutriName: 'Cysteine' },
  { foodbId: '12566', foodbName: 'L-Cystine', nutriName: 'Cystine' },
  { foodbId: '12538', foodbName: 'L-Glutamic acid', nutriName: 'Glutamic Acid' },
  { foodbId: '11859', foodbName: 'L-Histidine', nutriName: 'Histidine' },
  { foodbId: '12400', foodbName: 'L-Isoleucine', nutriName: 'Isoleucine' },
  { foodbId: '1946', foodbName: 'L-Leucine', nutriName: 'Leucine' },
  { foodbId: '474', foodbName: 'L-Lysine', nutriName: 'Lysine' },
  { foodbId: '12686', foodbName: 'L-Methionine', nutriName: 'Methionine' },
  { foodbId: '12742', foodbName: 'L-Serine', nutriName: 'Serine' },
  { foodbId: '12002', foodbName: 'L-Threonine', nutriName: 'Threonine' },
  { foodbId: '2250', foodbName: 'L-Tryptophan', nutriName: 'Tryptophan' },
  { foodbId: '446', foodbName: 'L-Tyrosine', nutriName: 'Tyrosine' },
  { foodbId: '3293', foodbName: 'Lactic acid', nutriName: 'Lactic Acid' },
  { foodbId: '1145', foodbName: 'Lactose', nutriName: 'Lactose' },
  { foodbId: '3778', foodbName: 'Lead', nutriName: 'Lead' },
  { foodbId: '14943', foodbName: 'Linalool', nutriName: 'Linalool' },
  { foodbId: '655', foodbName: 'Liquiritigenin', nutriName: 'Liquiritigenin' },
  { foodbId: '4182', foodbName: 'Lithium', nutriName: 'Lithium' },
  { foodbId: '15475', foodbName: 'Lutein', nutriName: 'Lutein' },
  { foodbId: '13258', foodbName: 'Luteolin', nutriName: 'Luteolin' },
  { foodbId: '14537', foodbName: 'Lycopene', nutriName: 'Lycopene' },
  { foodbId: '8115', foodbName: 'Malic acid', nutriName: 'Malic Acid' },
  { foodbId: '1193', foodbName: 'Maltose', nutriName: 'Maltose' },
  { foodbId: '2713', foodbName: 'Malvidin', nutriName: 'Malvidin' },
  { foodbId: '3637', foodbName: 'Manganese', nutriName: 'Manganese' },
  { foodbId: '3781', foodbName: 'Mercury', nutriName: 'Mercury' },
  { foodbId: '3654', foodbName: 'Molybdenum', nutriName: 'Molybdenum' },
  { foodbId: '12727', foodbName: 'Myricetin', nutriName: 'Myricetin' },
  { foodbId: '12636', foodbName: 'Myristoleic acid', nutriName: 'Myristoleic Acid' },
  { foodbId: '17741', foodbName: 'Neoglucobrassicin', nutriName: 'Neoglucobrassicin' },
  { foodbId: '15890', foodbName: 'Neoxanthin', nutriName: 'Neoxanthin' },
  { foodbId: '13447', foodbName: 'Nickel', nutriName: 'Nickel' },
  { foodbId: '12488', foodbName: 'Nicotinamide', nutriName: 'Niacinamide' },
  { foodbId: '1014', foodbName: 'Nicotinic acid', nutriName: 'Niacin' },
  { foodbId: '3307', foodbName: 'Nonanoic acid', nutriName: 'Pelargonic Acid' },
  { foodbId: '3337', foodbName: 'Octanoic acid', nutriName: 'Caprylic Acid' },
  { foodbId: '12861', foodbName: 'Oleic acid', nutriName: 'Oleic Acid' },
  { foodbId: '3655', foodbName: 'Ornithine', nutriName: 'Ornithine' },
  { foodbId: '8323', foodbName: 'Pantothenic acid', nutriName: 'Pantothenic Acid' },
  { foodbId: '12429', foodbName: 'Pelargonidin', nutriName: 'Pelargonidin' },
  { foodbId: '10035', foodbName: 'Pentadecanoic acid', nutriName: 'Pentadecanoic Acid' },
  { foodbId: '2753', foodbName: 'Peonidin', nutriName: 'Peonidin' },
  { foodbId: '2755', foodbName: 'Petunidin', nutriName: 'Petunidin' },
  { foodbId: '19148', foodbName: 'Phosphatidylcholine', nutriName: 'Phosphatidylcholine' },
  { foodbId: '3521', foodbName: 'Phosphorus', nutriName: 'Phosphorus' },
  { foodbId: '374', foodbName: 'Phytic acid', nutriName: 'Phytic Acid' },
  { foodbId: '12360', foodbName: 'Phytomenadione', nutriName: 'Vitamin K1' },
  { foodbId: '4844', foodbName: 'Pinene', nutriName: 'Pinene' },
  { foodbId: '3522', foodbName: 'Potassium', nutriName: 'Potassium' },
  { foodbId: '4902', foodbName: 'Proanthocyanidins', nutriName: 'Proanthocyanidins' },
  { foodbId: '12325', foodbName: 'Progoitrin', nutriName: 'Progoitrin' },
  { foodbId: '12378', foodbName: 'Pterostilbene', nutriName: 'Pterostilbene' },
  { foodbId: '1494', foodbName: 'Putrescine', nutriName: 'Putrescine' },
  { foodbId: '574', foodbName: 'Pyridoxine', nutriName: 'Vitamin B6' },
  { foodbId: '8294', foodbName: 'Pyruvic acid', nutriName: 'Pyruvic Acid' },
  { foodbId: '11907', foodbName: 'Quercetin', nutriName: 'Quercetin' },
  { foodbId: '661', foodbName: 'Raffinose', nutriName: 'Raffinose' },
  { foodbId: '12163', foodbName: 'Riboflavine', nutriName: 'Riboflavin' },
  { foodbId: '3696', foodbName: 'Saponins', nutriName: 'Saponins' },
  { foodbId: '12663', foodbName: 'Secoisolariciresinol', nutriName: 'Secoisolariciresinol' },
  { foodbId: '13403', foodbName: 'Selenium', nutriName: 'Selenium' },
  { foodbId: '3714', foodbName: 'Silicon', nutriName: 'Silicon' },
  { foodbId: '12322', foodbName: 'Sinigrin', nutriName: 'Sinigrin' },
  { foodbId: '3524', foodbName: 'Sodium', nutriName: 'Sodium' },
  { foodbId: '12323', foodbName: 'Stachyose', nutriName: 'Stachyose' },
  { foodbId: '1128', foodbName: 'Starch', nutriName: 'Starch' },
  { foodbId: '1936', foodbName: 'Stigmasterol', nutriName: 'Stigmasterol' },
  { foodbId: '1931', foodbName: 'Succinic acid', nutriName: 'Succinic Acid' },
  { foodbId: '1131', foodbName: 'Sucrose', nutriName: 'Sucrose' },
  { foodbId: '3718', foodbName: 'Sulfur', nutriName: 'Sulfur' },
  { foodbId: '1112', foodbName: 'Tartaric acid', nutriName: 'Tartaric Acid' },
  { foodbId: '3192', foodbName: 'Taurine', nutriName: 'Taurine' },
  { foodbId: '455', foodbName: 'Theobromine', nutriName: 'Theobromine' },
  { foodbId: '453', foodbName: 'Theophylline', nutriName: 'Theophylline' },
  { foodbId: '3723', foodbName: 'Tin', nutriName: 'Tin' },
  { foodbId: '14376', foodbName: 'Ursolic acid', nutriName: 'Ursolic Acid' },
  { foodbId: '3793', foodbName: 'Vanadium', nutriName: 'Vanadium' },
  { foodbId: '846', foodbName: 'Vanillic acid', nutriName: 'Vanillic Acid' },
  { foodbId: '5667', foodbName: 'Verbascose', nutriName: 'Verbascose' },
  { foodbId: '14728', foodbName: 'Violaxanthin', nutriName: 'Violaxanthin' },
  { foodbId: '1977', foodbName: 'Xanthine', nutriName: 'Xanthine' },
  { foodbId: '3730', foodbName: 'Zinc', nutriName: 'Zinc' },
  { foodbId: '13719', foodbName: 'alpha-Carotene', nutriName: 'Alpha-Carotene' },
  { foodbId: '15831', foodbName: 'alpha-Cryptoxanthin', nutriName: 'Alpha-Cryptoxanthin' },
  { foodbId: '12465', foodbName: 'alpha-Linolenic acid', nutriName: 'Alpha-Linolenic Acid' },
  { foodbId: '12068', foodbName: 'alpha-Spinasterol', nutriName: 'Alpha-Spinasterol' },
  { foodbId: '565', foodbName: 'alpha-Tocopherol', nutriName: 'Alpha-Tocopherol' },
  { foodbId: '14616', foodbName: 'beta-Carotene', nutriName: 'Beta-Carotene' },
  { foodbId: '12022', foodbName: 'beta-Cryptoxanthin', nutriName: 'Beta-Cryptoxanthin' },
  { foodbId: '12365', foodbName: 'beta-Sitosterol', nutriName: 'Beta-Sitosterol' },
  { foodbId: '4213', foodbName: 'delta-5-Avenasterol', nutriName: 'Delta-5-Avenasterol' },
  { foodbId: '14331', foodbName: 'gamma-Carotene', nutriName: 'Gamma-Carotene' },
  { foodbId: '2431', foodbName: 'gamma-Tocopherol', nutriName: 'Gamma-Tocopherol' },
  { foodbId: '1298', foodbName: 'gamma-Tocotrienol', nutriName: 'Gamma-Tocotrienol' },
  { foodbId: '2593', foodbName: 'p-Coumaric acid', nutriName: 'p-Coumaric Acid' },
];

async function main() {
  console.log('=== FooDB Compound Import ===\n');
  
  let addedCount = 0;
  let mappingCount = 0;
  let skippedCount = 0;
  
  // 1. Add new compounds and create mappings
  console.log('Adding new compounds...');
  
  for (const c of newCompounds) {
    // Check if compound exists
    const existing = await db.execute(
      sql`SELECT id FROM compounds WHERE LOWER(name) = LOWER(${c.name})`
    );
    
    let compoundId: string;
    
    if ((existing as any).length > 0) {
      compoundId = (existing as any)[0].id;
      // Skip logging for existing compounds to reduce noise
    } else {
      // Insert new compound
      const [inserted] = await db.insert(compounds).values({
        name: c.name,
        compoundType: c.type,
        unit: c.unit,
      }).returning();
      
      compoundId = inserted.id;
      console.log(`✅ ${c.name} (${c.type})`);
      addedCount++;
    }
    
    // Check if FooDB mapping exists
    const existingMapping = await db.execute(sql`
      SELECT id FROM compound_sources 
      WHERE external_source = 'FOODB' AND external_id = ${c.foodbId}
    `);
    
    if ((existingMapping as any).length === 0) {
      await db.insert(compoundSources).values({
        compoundId: compoundId,
        externalSource: 'FOODB',
        externalId: c.foodbId,
        sourceName: c.name,
        isCanonical: true,
      });
      mappingCount++;
    } else {
      skippedCount++;
    }
  }
  
  // 2. Create mappings for existing compounds
  console.log('\nMapping existing compounds...');
  
  for (const m of existingMappings) {
    // Find compound by name
    const compound = await db.execute(
      sql`SELECT id FROM compounds WHERE LOWER(name) = LOWER(${m.nutriName})`
    );
    
    if ((compound as any).length === 0) {
      console.log(`❌ Not found: ${m.nutriName}`);
      continue;
    }
    
    const compoundId = (compound as any)[0].id;
    
    // Check if mapping exists
    const existingMapping = await db.execute(sql`
      SELECT id FROM compound_sources 
      WHERE external_source = 'FOODB' AND external_id = ${m.foodbId}
    `);
    
    if ((existingMapping as any).length === 0) {
      await db.insert(compoundSources).values({
        compoundId: compoundId,
        externalSource: 'FOODB',
        externalId: m.foodbId,
        sourceName: m.foodbName,
        isCanonical: true,
      });
      console.log(`✅ ${m.foodbId} → ${m.nutriName}`);
      mappingCount++;
    } else {
      skippedCount++;
    }
  }
  
  // 3. Summary
  const finalCount = await db.execute(sql`
    SELECT external_source, COUNT(*) as count
    FROM compound_sources
    GROUP BY external_source
    ORDER BY external_source
  `);
  
  const compoundCount = await db.execute(sql`SELECT COUNT(*) as count FROM compounds`);
  
  console.log('\n=== Summary ===');
  console.log(`New compounds added: ${addedCount}`);
  console.log(`Mappings created: ${mappingCount}`);
  console.log(`Skipped (existing): ${skippedCount}`);
  console.log(`\nTotal compounds: ${(compoundCount as any)[0]?.count}`);
  console.log('\nMappings by source:');
  (finalCount as any).forEach((r: any) => {
    console.log(`  ${r.external_source}: ${r.count}`);
  });
}

main().then(() => process.exit(0)).catch(console.error);
